//
//  AudioMobileListenViewController.h
//  Audio-Mobile
//
//

#import <UIKit/UIKit.h>
#import "AudioMobileRestAPIManager.h"
#import "AudioMobilePlaybackViewController.h"

@interface AudioMobileListenViewController :  UIViewController<UISearchBarDelegate,AudioMobileRestAsyncResponseNotifier,UITableViewDataSource,UITableViewDelegate> {
    BOOL shouldBeginEditing;
}
@property (weak, nonatomic) IBOutlet UITableView *searchResultsTable;
 
@property (weak, nonatomic) IBOutlet UISearchBar *searchBar;

@property (strong, nonatomic) NSMutableArray* defaultNodeList; //this is the list of nodes generated by users the logged in user listens to, in reverse chronological order.

@property (strong, nonatomic) NSArray* customSearchResults;

@property (nonatomic) bool customSearchMode;

@end
